import type { Profile } from "@/lib/types";

const chromosomes = [
  { id: "1", snps: 59310 },
  { id: "2", snps: 57780 },
  { id: "3", snps: 47299 },
  { id: "4", snps: 40526 },
  { id: "5", snps: 42169 },
  { id: "6", snps: 48272 },
  { id: "7", snps: 38215 },
  { id: "8", snps: 37086 },
  { id: "9", snps: 32878 },
  { id: "10", snps: 39160 },
  { id: "11", snps: 36704 },
  { id: "12", snps: 35618 },
  { id: "13", snps: 27912 },
  { id: "14", snps: 23377 },
  { id: "15", snps: 21702 },
  { id: "16", snps: 22822 },
  { id: "17", snps: 20296 },
  { id: "18", snps: 21765 },
  { id: "19", snps: 15138 },
  { id: "20", snps: 18461 },
  { id: "21", snps: 10257 },
  { id: "22", snps: 10507 },
  { id: "X", snps: 18022 },
];

const snps = chromosomes.reduce((n, c) => n + c.snps, 0);

export const simon: Profile = {
  slug: "simon",
  firstName: "Simon",
  status: "published",
  tested: "FamilyTreeDNA · myOrigins v3 · mtFull Sequence · Big Y",
  tagline: "North in the autosomes. Two older threads.",
  lede: "Almost every autosomal stretch is painted Scandinavian. Under that sit a Swedish motherline from the Middle Ages and a rare paternal twig on the Atlantic R-L21 tree — plus the X that only a mother can give a son.",
  heroImage: "/images/hero-fjord.jpg",
  heroAlt: "A winter fjord under a faint aurora, no people in the frame",
  heroStats: [
    { label: "Scandinavia", value: "99%", color: "aurora" },
    { label: "Fatherline", value: "R-BY67151", shortValue: "BY67151", color: "ice" },
    { label: "Motherline", value: "U5b1b1a", shortValue: "U5b1b1a", color: "rose" },
  ],
  originsHeadline: {
    lead: "One hundred percent Europe.",
    accent: "Ninety-nine of it northern.",
  },
  originsLede:
    "FamilyTreeDNA myOrigins v3 paints Simon as entirely European, and almost entirely Scandinavian. The leftover traces are smaller than one percent each — the slices the method itself warns are easy to misread.",
  origins: [
    {
      id: "scandinavia",
      label: "Scandinavia",
      percent: 99,
      color: "#7ec8a3",
      image: "/images/scandinavia.jpg",
      kicker: "The whole house",
      summary:
        "Nearly all of Simon’s autosomal ancestry sits with Scandinavian reference populations — Denmark, Sweden, Norway, and the wider Nordic peninsula.",
      detail:
        "FamilyTreeDNA’s myOrigins v3 places 99% of his autosomal DNA with Scandinavian references. That is not a passport. It is a statistical resemblance: long shared stretches of chromosome that look most like people whose deep roots are in the North. The Y chromosome and the mitochondria tell older, narrower stories that this number cannot see.",
    },
    {
      id: "baltic",
      label: "Baltic",
      percent: 0.5,
      display: "<1%",
      color: "#8ea4c8",
      image: "/images/baltic-shore.jpg",
      kicker: "A trace next door",
      summary:
        "A trace assigned to Baltic references — Estonia, Latvia, Lithuania. FamilyTreeDNA flags traces as the easiest slices to invent.",
      detail:
        "Less than one percent. The method’s own paper treats traces as fragile. It may be real east-Baltic sharing at the edge of Scandinavia, or noise in a genome that is already 99% northern. It is a whisper, not a chapter.",
    },
    {
      id: "sephardic",
      label: "Sephardic Jewish",
      percent: 0.5,
      display: "<1%",
      color: "#c45c6a",
      image: "/images/france-bridge.jpg",
      kicker: "A labelled whisper",
      summary:
        "A trace under the Sephardic Jewish label. FamilyTreeDNA warns that traces this small are especially likely to be misattributed.",
      detail:
        "Less than one percent, mapped toward Iberia. Traces are the first thing to drop when reference panels change. This site does not read it as a family story. It is a labelled leftover on a genome otherwise painted Scandinavian.",
    },
  ],
  ancientHeadline: {
    lead: "Half forager.",
    mid: "Then the fields.",
    end: "Then a thin horse.",
  },
  ancientLede:
    "Under the modern map is a much older recipe. FamilyTreeDNA splits European autosomal DNA into three deep streams. Simon’s mix is heavy on hunter-gatherer, then farmer, with a modest Metal Age pulse.",
  ancientOrigins: [
    {
      id: "hunter",
      label: "Hunter-Gatherer",
      percent: 49,
      color: "#c45c6a",
      image: "/images/hunter-gatherer.jpg",
      emblem: "/images/emblem-hunter.jpg",
      era: "Pleistocene → Mesolithic",
      when: "From about 45,000 years ago",
      summary:
        "Almost half of Simon’s European autosomal ancestry still resembles the first modern humans who walked a thawing continent — the same deep layer that shows up in La Brana, Loschbour, and Motala.",
      detail:
        "FamilyTreeDNA’s Hunter-Gatherer component is their stand-in for Western hunter-gatherers. Forty-nine percent is loud for a living northern European. The motherline haplogroup U5 is itself a classic hunter-gatherer maternal family in Mesolithic Europe — Cheddar Man, Motala, Fannerup — so the autosomes and the mitochondria rhyme, without being the same fact.",
    },
    {
      id: "farmer",
      label: "Early Farmer",
      percent: 39,
      color: "#7ec8a3",
      image: "/images/farmer.jpg",
      emblem: "/images/emblem-farmer.jpg",
      era: "Neolithic",
      when: "About 8,000–7,000 years ago",
      summary:
        "Wheat, pottery, and settled valleys. Farmers moved from the Near East along Anatolia into the Danube and on toward Spain.",
      detail:
        "Thirty-nine percent follows that expansion — Linear Pottery and Funnel Beaker worlds that remade Europe’s diet and genes. Ötzi sits on this broad farmer movement. In living Scandinavians the farmer layer is usually large; here it is the second voice, not the first.",
    },
    {
      id: "invader",
      label: "Metal Age Invader",
      percent: 12,
      color: "#8ea4c8",
      image: "/images/yamnaya.jpg",
      emblem: "/images/emblem-invader.jpg",
      era: "Bronze Age",
      when: "About 5,800 years ago",
      summary:
        "A smaller pulse from the Pontic–Caspian steppe: horses, wagons, and bronze. FamilyTreeDNA’s name is dramatic; the academic label is Yamnaya-related ancestry.",
      detail:
        "Twelve percent is modest next to the hunter-gatherer half. The paternal haplogroup, though, is R1b — the Y family that rode that steppe expansion into western Europe. Autosomes and Y do not have to agree in volume. A single fatherline can sit on a steppe Y while most of the rest of the genome stayed northern.",
    },
  ],
  haplogroup: {
    id: "U5b1b1a",
    parent: "U5b1b1a+7385",
    pathLabel: "U > U5 > U5b > U5b1 > U5b1b1a +7385 +16519",
    formed: "branched from U5b1b1a+7385 around 1200 BCE",
    headline: "A Swedish motherline from the Viking Age.",
    tmrca: { meanLabel: "850 CE", ci95: "see note" },
    testers: { total: 15, known: "8 naming Sweden, 1 Finland" },
    rarityNote:
      "Fifteen testers sit on U5b1b1a+7385+16519. The living geography is Swedish, with one Finnish kit. The parent branch is already Bronze Age; this twig is medieval.",
  },
  haploPath: [
    {
      haplogroup: "L",
      yearLabel: "141,000 BCE",
      year: -141000,
      era: "Out of Africa",
      place: "East Africa",
      copy: "Mitochondrial Eve in the broad sense: the mother of all living mitochondrial lines. Not a first woman. A bottleneck on one thread.",
    },
    {
      haplogroup: "L3",
      yearLabel: "64,000 BCE",
      year: -64000,
      era: "Out of Africa",
      place: "East Africa",
      copy: "L3 is the African mother of the two lineages that left: N and M. From here the story walks north.",
    },
    {
      haplogroup: "N",
      yearLabel: "57,000 BCE",
      year: -57000,
      era: "Out of Africa",
      place: "Near East",
      copy: "N is the Eurasian door. Most European motherlines, including U, sit downstream.",
    },
    {
      haplogroup: "U",
      yearLabel: "49,000 BCE",
      year: -49000,
      era: "Upper Paleolithic",
      place: "West Eurasia",
      copy: "U is an old European family. Its daughters hunted Ice Age Europe long before farming.",
    },
    {
      haplogroup: "U5",
      yearLabel: "40,000 BCE",
      year: -40000,
      era: "Upper Paleolithic",
      place: "Europe",
      copy: "U5 is the classic Western hunter-gatherer motherline. Ice, refugia, and later the first settlers of a thawing north.",
    },
    {
      haplogroup: "U5b",
      yearLabel: "20,000 BCE",
      year: -20000,
      era: "Upper Paleolithic",
      place: "Europe",
      copy: "U5b is the western sister of U5a. Mesolithic Britain, Scandinavia, and the Atlantic façade still carry it.",
    },
    {
      haplogroup: "U5b1",
      yearLabel: "12,000 BCE",
      year: -12000,
      era: "Late Stone Age",
      place: "Europe",
      copy: "Cheddar Man sits on U5b1. After the ice, this branch is already in Britain and the North Sea world.",
    },
    {
      haplogroup: "U5b1b1",
      yearLabel: "6350 BCE",
      year: -6350,
      era: "Late Stone Age",
      place: "Scandinavia",
      copy: "Fannerup 855, a Mesolithic man from Jutland, sits here. The motherline is already Danish thousands of years before the twig that testers live on.",
    },
    {
      haplogroup: "U5b1b1a",
      yearLabel: "1400 BCE",
      year: -1400,
      era: "Metal Ages",
      place: "Scandinavia",
      copy: "The named family before the last two mutations. Bronze Age north. From here the clock is no longer geological.",
    },
    {
      haplogroup: "U5b1b1a+16519",
      yearLabel: "850 CE",
      year: 850,
      era: "Middle Ages",
      place: "Sweden",
      copy: "The living twig. FamilyTreeDNA dates the most recent woman of this exact branch around 850 CE. Fifteen testers; the named origins are Sweden and Finland.",
    },
  ],
  haploMapPoints: [
    { x: 52, y: 72, label: "Eve" },
    { x: 54, y: 58, label: "L3" },
    { x: 57, y: 48, label: "N" },
    { x: 60, y: 40, label: "U" },
    { x: 58, y: 30, label: "U5" },
    { x: 53, y: 20, label: "U5b1b1a" },
  ],
  motherlineMapCaption:
    "A schematic walk: East Africa → Near East → haplogroup U → U5 in Ice Age Europe → a Swedish medieval twig. Not a GPS track — a mitochondrial route of daughters.",
  motherlineSpotlights: [
    {
      img: "/images/sweden-winter.jpg",
      title: "A Swedish twig",
      copy: "Fifteen testers. Eight name Sweden, one Finland. The last woman of this exact branch likely lived around 850 CE — late Iron Age / early medieval north.",
    },
    {
      img: "/images/hunter-gatherer.jpg",
      title: "U5 before farms",
      copy: "U5 is the hunter-gatherer motherline of western Europe. Cheddar Man, Motala, and a Mesolithic Dane at Fannerup all sit on older U5b branches of the same family.",
    },
    {
      img: "/images/medieval-denmark.jpg",
      title: "A queen on U5b1",
      copy: "Mechtilde of Holstein, queen of Denmark in the thirteenth century, shares U5b1 — not the medieval twig, the older node at 12,000 BCE. A fun fact, not a cousin.",
    },
  ],
  yHaplogroup: {
    id: "R-BY67151",
    parent: "R-S7293",
    pathLabel: "R-P312 > L21 > DF13 > FTT9 > BY197676 > S7293 > BY67151",
    formed: "branched from R-S7293 around 1050 BCE",
    headline: "A rare paternal twig, dated to about 1500 CE.",
    tmrca: { meanLabel: "1482 CE", ci95: "1168–1703 CE" },
    testers: { total: 3, known: "Norway 2, England 1" },
    rarityNote:
      "Three Big Y testers on R-BY67151. FamilyTreeDNA lists 32 equivalent SNPs for the twig; the February 2020 Big Y VCF calls every one of them derived. The line left the huge DF13 oak at FTT9 in the Early Bronze Age, then thinned through BY197676 and S7293. The autosomes are 99% Scandinavian. The Y is Atlantic.",
  },
  yHaploPath: [
    {
      haplogroup: "Y-Adam",
      yearLabel: "232,000 BCE",
      year: -232000,
      era: "Out of Africa",
      place: "East Africa",
      copy: "The father of all living Y lines, in the same bottleneck sense as mitochondrial Eve. Not the first man.",
    },
    {
      haplogroup: "BT",
      yearLabel: "86,000 BCE",
      year: -86000,
      era: "Out of Africa",
      place: "East Africa",
      copy: "BT is the trunk that most non-A00 men sit on. From here the walk out of Africa begins.",
    },
    {
      haplogroup: "F",
      yearLabel: "46,000 BCE",
      year: -46000,
      era: "Upper Paleolithic",
      place: "Near East",
      copy: "F is the Eurasian radiation. G, H, I, J, and K all fork from this neighbourhood.",
    },
    {
      haplogroup: "P",
      yearLabel: "34,000 BCE",
      year: -34000,
      era: "Upper Paleolithic",
      place: "West Asia",
      copy: "P is the father of Q and R. The steppe and the Americas sit downstream of this node, on different sons.",
    },
    {
      haplogroup: "R-M207",
      yearLabel: "25,000 BCE",
      year: -25000,
      era: "Upper Paleolithic",
      place: "Eurasia",
      copy: "Haplogroup R. One son becomes R1a, another R1b. Simon’s line is R1b.",
    },
    {
      haplogroup: "R-M343",
      yearLabel: "17,000 BCE",
      year: -16981,
      era: "Upper Paleolithic",
      place: "West Eurasia",
      copy: "R1b. Tutankhamun is placed on this ancient node — a fun fact about 17,000 BCE, not the New Kingdom.",
    },
    {
      haplogroup: "R-P312",
      yearLabel: "2840 BCE",
      year: -2839,
      era: "Metal Ages",
      place: "Atlantic Europe",
      copy: "P312 is the western Bell Beaker fatherline. It is the door R1b took into Atlantic Europe. Darwin and Crick sit on the older R-M269; P312 is the son that went west.",
    },
    {
      haplogroup: "R-L21",
      yearLabel: "2650 BCE",
      year: -2648,
      era: "Metal Ages",
      place: "Atlantic Europe",
      copy: "L21 is the big Atlantic branch of P312. It is common in Britain and Ireland, and present in Brittany and Norway. This is where Simon’s Y leaves generic western R1b and takes the Insular door.",
    },
    {
      haplogroup: "R-DF13",
      yearLabel: "2560 BCE",
      year: -2560,
      era: "Metal Ages",
      place: "Atlantic Europe",
      copy: "DF13 is an oak: tens of thousands of living testers and hundreds of ancient genomes. Early Bronze Age men at Rathlin, Yarnton, and Amesbury sit on this node. Simon’s line is about to leave the oak.",
    },
    {
      haplogroup: "R-FTT9",
      yearLabel: "2535 BCE",
      year: -2535,
      era: "Metal Ages",
      place: "Atlantic Europe",
      copy: "The thinning. FamilyTreeDNA’s tree (August 2026) puts fifteen Big Y testers on FTT9, against tens of thousands on DF13. England, Norway, Scotland. A rare Early Bronze Age fork, not a surname.",
    },
    {
      haplogroup: "R-BY197676",
      yearLabel: "1930 BCE",
      year: -1928,
      era: "Metal Ages",
      place: "Atlantic Europe",
      copy: "Nine testers. England and Norway. The clock here is the middle Bronze Age. The February 2020 VCF calls eight of the nine equivalent SNPs derived at high quality; the ninth is derived at lower depth.",
    },
    {
      haplogroup: "R-S7293",
      yearLabel: "1050 BCE",
      year: -1047,
      era: "Metal Ages",
      place: "Atlantic Europe",
      copy: "Six Big Y testers, then a split. Thomas Powys sits on the sister branch R-FT287223. Simon sits on BY67151. About 1 in 120,000 testers share a node this close. Still a Metal Age fork, not a courtroom.",
    },
    {
      haplogroup: "R-BY67151",
      yearLabel: "1500 CE",
      year: 1482,
      era: "Middle Ages",
      place: "Norway",
      copy: "Three testers. Norway 2, England 1. FamilyTreeDNA’s clock for the last man of this exact branch is 1482 CE (95% interval 1168–1703). Thirty-two equivalent SNPs; the 2020 Big Y callset has all of them derived. A late medieval paternal family on an Atlantic Y, inside a 99% Scandinavian autosomal genome.",
    },
  ],
  yHaploMapPoints: [
    { x: 48, y: 76, label: "Adam" },
    { x: 52, y: 62, label: "R" },
    { x: 62, y: 46, label: "L21" },
    { x: 58, y: 32, label: "FTT9" },
    { x: 54, y: 18, label: "BY67151" },
  ],
  fatherlineMapCaption:
    "A schematic walk: East Africa → R1b → Bell Beaker P312 → Atlantic L21/DF13 → the thin FTT9 fork → a late-medieval twig with testers in Norway and England. Not a surname history. A Y route of sons.",
  fatherlineSpotlights: [
    {
      img: "/images/british-isles.jpg",
      title: "An Atlantic Y",
      copy: "P312, L21 and DF13 are the Beaker-age western oak of R1b. Simon’s autosomes do not look British. His Y sits on that oak anyway — a single paternal thread, not the rest of the genome.",
    },
    {
      img: "/images/bronze-plain.jpg",
      title: "The oak thins",
      copy: "FTT9 has fifteen Big Y testers. BY197676 has nine. S7293 has six. BY67151 has three. The February 2020 regions file covers 14.9 million bases of chrY; the named terminal SNPs are all derived there.",
    },
    {
      img: "/images/scandinavia.jpg",
      title: "A judge on the sister branch",
      copy: "Thomas Powys (1649–1719) is R-FT287223, the other son of S7293. FamilyTreeDNA still counts that as a rare notable connection. Three thousand years of fathers, not a courtroom.",
    },
  ],
  connectionsLede:
    "FamilyTreeDNA lists notable and archaeological people who share a Y or mitochondrial ancestor with Simon. These are not cousins in any family sense. They are fun facts about threads that are thousands of years long. Living match names are not shown here.",
  connections: [
    {
      id: "powys",
      name: "Thomas Powys",
      dates: "1649–1719 CE",
      kind: "notable",
      rarity: "rare",
      line: "paternal",
      shared: "R-S7293",
      sharedYear: "1050 BCE",
      place: "England",
      image: "/images/british-isles.jpg",
      blurb:
        "Attorney general and judge in late Stuart England, including the trial of the Seven Bishops. His Big Y twig is R-FT287223, the sister of Simon’s R-BY67151. They share R-S7293, a Metal Age paternal node. FamilyTreeDNA counts that closeness as about 1 in 120,000 testers. Not a legal ancestor. A fork at 1050 BCE.",
    },
    {
      id: "darwin",
      name: "Charles Darwin",
      dates: "1809–1882 CE",
      kind: "notable",
      rarity: "common",
      line: "paternal",
      shared: "R-M269",
      sharedYear: "4450 BCE",
      place: "England",
      image: "/images/british-isles.jpg",
      blurb:
        "The naturalist of On the Origin of Species. The shared Y node is R-M269, the great western European fatherline, around 4450 BCE. Most western European men sit somewhere on this oak. A deep-time fun fact, not a Beagle ticket.",
    },
    {
      id: "crick",
      name: "Francis Crick",
      dates: "1916–2004 CE",
      kind: "notable",
      rarity: "common",
      line: "paternal",
      shared: "R-M269",
      sharedYear: "4450 BCE",
      place: "England",
      image: "/images/dna-abstract.jpg",
      blurb:
        "Co-discoverer of the double helix. Again the shared node is R-M269 at 4450 BCE — the same western European Y family, not the Cavendish Laboratory.",
    },
    {
      id: "tut",
      name: "Tutankhamun",
      dates: "1341–1323 BCE",
      kind: "ancient",
      rarity: "common",
      line: "paternal",
      shared: "R-M343",
      sharedYear: "17,000 BCE",
      place: "Thebes, Egypt",
      image: "/images/nile-thebes.jpg",
      blurb:
        "The boy king of the Eighteenth Dynasty. FamilyTreeDNA places the shared paternal ancestor at R-M343 (R1b), about 17,000 BCE. That is the Ice Age father of western European R1b, not the Valley of the Kings.",
    },
    {
      id: "rathlin",
      name: "Rathlin 1",
      dates: "2026–1885 BCE",
      kind: "ancient",
      rarity: "common",
      line: "paternal",
      shared: "R-DF13",
      sharedYear: "2560 BCE",
      place: "Rathlin Island",
      image: "/images/ireland.jpg",
      blurb:
        "An Early Bronze Age man from Rathlin Island (Cassidy et al. 2016). His Y is R-DF21, a brother of Simon’s FTT9 under the same DF13 oak. About 1 in 9 testers share a node this wide. A Beaker-period Irish genome on the Atlantic fatherline — not a Viking, and not a close cousin.",
    },
    {
      id: "fannerup",
      name: "Fannerup 855",
      dates: "4671–4253 BCE",
      kind: "ancient",
      rarity: "rare",
      line: "maternal",
      shared: "U5b1b1",
      sharedYear: "6350 BCE",
      place: "Jutland, Denmark",
      image: "/images/hunter-gatherer.jpg",
      blurb:
        "A Mesolithic man from Fannerup, Jutland (Allentoft et al. 2024). He sits on U5b1b1, the parent of Simon’s living twig. About 1 in 148 testers share a node this close. A Danish hunter-gatherer on the same motherline family, five thousand years before 850 CE.",
    },
    {
      id: "cheddar",
      name: "Cheddar Man",
      dates: "8607–7982 BCE",
      kind: "ancient",
      rarity: "common",
      line: "maternal",
      shared: "U5b1",
      sharedYear: "12,000 BCE",
      place: "Cheddar Gorge",
      image: "/images/british-isles.jpg",
      blurb:
        "Mesolithic Britain, before farms. Cheddar Man is U5b1. Simon’s line is a much later Swedish daughter of that same Ice Age mother. Dark skin and blue eyes in the genomic reconstruction are his story, not Simon’s face.",
    },
    {
      id: "mechtilde",
      name: "Mechtilde of Holstein",
      dates: "1218–1288 CE",
      kind: "notable",
      rarity: "common",
      line: "maternal",
      shared: "U5b1",
      sharedYear: "12,000 BCE",
      place: "Denmark",
      image: "/images/medieval-denmark.jpg",
      blurb:
        "Queen of Denmark as wife of Abel. The shared maternal node is U5b1 at 12,000 BCE — the same depth as Cheddar Man, not the thirteenth-century court. A crown on an old hunter-gatherer motherline.",
    },
    {
      id: "vistegutten",
      name: "Vistegutten",
      dates: "6300–6000 BCE",
      kind: "ancient",
      rarity: "common",
      line: "maternal",
      shared: "U5a'b",
      sharedYear: "28,000 BCE",
      place: "Rogaland, Norway",
      image: "/images/scandinavia.jpg",
      blurb:
        "The Viste boy, Norway’s best-preserved Stone Age skeleton, from Vistehola in Rogaland. The shared node is U5a'b at 28,000 BCE. A Mesolithic Norwegian child on the broad U5 family, not the Swedish medieval twig.",
    },
    {
      id: "motala",
      name: "Motala Woman",
      dates: "5898–5531 BCE",
      kind: "ancient",
      rarity: "common",
      line: "maternal",
      shared: "U5a'b",
      sharedYear: "28,000 BCE",
      place: "Sweden",
      image: "/images/sweden-winter.jpg",
      blurb:
        "Motala 1, a Mesolithic woman from the settlement by lake Vättern. U5a'b again — the Ice Age mother of U5a and U5b. Hunter-gatherer Sweden, seven thousand years ago.",
    },
    {
      id: "byrsa",
      name: "Young Man of Byrsa",
      dates: "525–500 BCE",
      kind: "ancient",
      rarity: "common",
      line: "maternal",
      shared: "U5b",
      sharedYear: "20,000 BCE",
      place: "Carthage",
      image: "/images/bronze-plain.jpg",
      blurb:
        "Ariche, a young Phoenician man buried at Byrsa Hill in Carthage. Shared node U5b at 20,000 BCE. A Punic burial on a European hunter-gatherer motherline that had already walked a long way from the ice.",
    },
    {
      id: "neanderthal",
      name: "Neanderthal",
      dates: "~40,000 years ago",
      kind: "deep",
      rarity: "common",
      line: "deep",
      shared: "L'AA / A000-T",
      sharedYear: "379,000 BCE",
      place: "Eurasia",
      image: "/images/hunter-gatherer.jpg",
      blurb:
        "Every living person shares this depth on the mitochondrial tree, and every living man shares the corresponding Y split. A cousin on a far older hominin branch, not a private family secret.",
    },
  ],
  chromosomes,
  genome: {
    snps,
    build: "Build 37 autosomal export",
    painting:
      "The chip reads autosomes and X — 725,276 SNPs here. A son’s X is the X his mother gave him. Y is not on this microarray; it was sequenced separately as Big Y. The February 2020 regions file covers 14.9 million bases of chrY that passed QC. All 32 equivalent SNPs for R-BY67151 are derived in that callset. Continent-scale painting is Scandinavian, with two traces under one percent.",
  },
};
