import type { Locale } from "@/lib/i18n/config";

const copy = {
  en: {
    common: {
      skip: "Skip to story",
      original: "Original",
      story: "Story",
      dossier: "Dossier",
      journey: "Journey",
      language: "Dansk",
      evidence: "Evidence",
      source: "Source",
      sources: "Sources",
      asOf: "As of",
      privateAggregate: "Verified from a private export; only the aggregate is public.",
      uncertainty: "What this cannot prove",
      method: "Method",
      back: "All stories",
    },
    v2: {
      eyebrow: "Story + evidence · Simon",
      title: "Three tests. Three scales of time.",
      lede: "A northern autosomal picture, an old maternal thread, and a rare Atlantic paternal branch — read together, but never mistaken for the same kind of evidence.",
      snapshot: "The short version",
      snapshotTitle: "Almost all North. Two lines go much deeper.",
      origins: "Origins",
      originsTitle: "A strong signal and two traces.",
      originsBody: "FamilyTreeDNA compares Simon's autosomal markers with reference populations. The dominant resemblance is Scandinavian. The two remaining labels are thresholds below one percent, not exact slices and not family-tree discoveries.",
      lines: "Two family lines",
      linesTitle: "One mother. One father. Not the whole genome.",
      maternalBody: "The exact maternal terminal branch is centered in the early-medieval period. Current testers cluster around Sweden, but their reported origins do not turn the shared woman into a known Swedish Viking.",
      paternalBody: "The Y line sits on the Atlantic R-L21 oak and ends in a very small branch. Its Bronze Age formation and the late-medieval common ancestor of current testers are different dates.",
      ancient: "Ancient context",
      ancientTitle: "A vendor model of three deep European streams.",
      ancientBody: "These are broad model components, not literal ancestors. Ancient genomes help explain European population change; they do not identify the people in Simon's family tree.",
      method: "Evidence & method",
      methodTitle: "A story with its seams showing.",
      methodBody: "The public page contains approved aggregates only. Raw genotype rows and full sequences stay local. Every material figure carries a source, a precision rule, and an as-of date where the underlying tree can change.",
      callout: "The honest headline",
      calloutBody: "The evidence is strongest when it says what kind of test produced it — and quietest where a trace, date range, or modern tester location cannot bear a larger story.",
    },
    v3: {
      eyebrow: "Research dossier · Simon · 2026-09-02",
      title: "Evidence before interpretation.",
      lede: "A technical view of the same story: datasets, quality summaries, lineages, branch dates, source classes, and explicit limits.",
      overview: "Dossier overview",
      modern: "Modern autosomal estimate",
      ancient: "Vendor ancient components",
      qc: "Dataset quality summary",
      maternal: "Maternal lineage",
      paternal: "Paternal lineage",
      connections: "Context and connections",
      sourceRegister: "Source register",
      completePath: "Documented path",
      selectedPath: "Selected milestones",
      formation: "Branch formation",
      tmrca: "Current-tester TMRCA",
      testers: "Current testers",
      direct: "Peer-reviewed context",
      illustrative: "Vendor-illustrative",
      result: "Result",
      precision: "Precision",
      evidenceState: "Evidence state",
      test: "Dataset",
      measure: "Measure",
      note: "Interpretation note",
    },
    v4: {
      eyebrow: "An evidence journey · Simon",
      title: "One genome is not one story.",
      lede: "Move from hundreds of thousands of autosomal markers to two single-line inheritances — and watch the scale of time change beneath your feet.",
      begin: "Begin the journey",
      scene1: "01 · The tests",
      scene1Title: "Three instruments look at three different inheritances.",
      scene1Body: "Family Finder samples markers across the autosomes. mtFull follows one unbroken maternal thread. Big Y follows one paternal thread. They overlap in a person, not in what they measure.",
      scene2: "02 · The population estimate",
      scene2Title: "The broadest signal points north.",
      scene2Body: "Ninety-nine percent resembles Scandinavian reference populations. Two labels remain below one percent — visible as traces, never inflated into exact slices.",
      scene3: "03 · Ancient Europeans",
      scene3Title: "Foragers, farmers, then steppe-related ancestry.",
      scene3Body: "A vendor model divides the European autosomes into three deep streams. The percentages describe statistical components, while ancient genomes supply historical context rather than named ancestors.",
      scene4: "04 · The maternal line",
      scene4Title: "A thread carried by mothers reaches a small medieval branch.",
      scene4Body: "The terminal mtDNA branch is U5b1b1a+7385+16519. Its time estimate centers on 836 CE, with uncertainty extending from 505 to 1127 CE.",
      scene5: "05 · The paternal line",
      scene5Title: "An Atlantic oak narrows to three current testers.",
      scene5Body: "R-BY67151 formed from an older branch long before the common ancestor estimated for today's testers. The VCF supports all 32 defining variants; two carry quality flags.",
      scene6: "06 · The boundary",
      scene6Title: "Evidence can orient a search. It cannot name the missing people.",
      scene6Body: "Countries are self-reported clues, dates are probability ranges, and deep shared nodes are not close kin. The raw DNA remains private; this journey publishes only checked aggregates.",
      evidenceTray: "Open evidence trail",
      closing: "The story becomes more useful when uncertainty is part of the map.",
    },
  },
  da: {
    common: {
      skip: "Spring til historien",
      original: "Original",
      story: "Fortælling",
      dossier: "Dossier",
      journey: "Rejse",
      language: "English",
      evidence: "Evidens",
      source: "Kilde",
      sources: "Kilder",
      asOf: "Pr.",
      privateAggregate: "Bekræftet fra en privat eksport; kun aggregatet er offentligt.",
      uncertainty: "Hvad det ikke kan bevise",
      method: "Metode",
      back: "Alle historier",
    },
    v2: {
      eyebrow: "Fortælling + evidens · Simon",
      title: "Tre tests. Tre tidsskalaer.",
      lede: "Et nordligt autosomalt billede, en gammel morlinje og en sjælden atlantisk fargren — læst sammen, men aldrig forvekslet med den samme slags evidens.",
      snapshot: "Den korte version",
      snapshotTitle: "Næsten helt nord. To linjer går langt dybere.",
      origins: "Oprindelse",
      originsTitle: "Et stærkt signal og to spor.",
      originsBody: "FamilyTreeDNA sammenligner Simons autosomale markører med referencebefolkninger. Den dominerende lighed er skandinavisk. De to resterende mærkater er grænser under én procent, ikke præcise skiver eller slægtsfund.",
      lines: "To familielinjer",
      linesTitle: "Én mor. Én far. Ikke hele genomet.",
      maternalBody: "Den præcise terminale morgren har centrum i den tidlige middelalder. Nutidige testere samler sig omkring Sverige, men deres oplyste oprindelse gør ikke den fælles kvinde til en kendt svensk viking.",
      paternalBody: "Y-linjen sidder på det atlantiske R-L21-egetræ og ender i en meget lille gren. Dens dannelse i bronzealderen og den senmiddelalderlige fælles forfader for nutidige testere er to forskellige datoer.",
      ancient: "Oldtidskontekst",
      ancientTitle: "En leverandørmodel af tre dybe europæiske strømme.",
      ancientBody: "Det er brede modelkomponenter, ikke bogstavelige forfædre. Oldtidsgenomer hjælper med at forklare Europas befolkningsskift; de identificerer ikke personer i Simons stamtræ.",
      method: "Evidens & metode",
      methodTitle: "En fortælling, hvor sømmene kan ses.",
      methodBody: "Den offentlige side indeholder kun godkendte aggregater. Rå genotyper og hele sekvenser forbliver lokale. Hvert vigtigt tal har en kilde, en præcisionsregel og en dato, når træet kan ændre sig.",
      callout: "Den ærlige overskrift",
      calloutBody: "Evidensen er stærkest, når den fortæller, hvilken test der skabte den — og mest stille, når et spor, et datointerval eller en nutidig testerplacering ikke kan bære en større historie.",
    },
    v3: {
      eyebrow: "Forskningsdossier · Simon · 02.09.2026",
      title: "Evidens før fortolkning.",
      lede: "Et teknisk blik på den samme historie: datasæt, kvalitetsmål, linjer, grendatoer, kildetyper og tydelige begrænsninger.",
      overview: "Dossieroversigt",
      modern: "Moderne autosomalt estimat",
      ancient: "Leverandørens oldtidskomponenter",
      qc: "Kvalitetsoversigt for datasæt",
      maternal: "Morlinje",
      paternal: "Farlinje",
      connections: "Kontekst og forbindelser",
      sourceRegister: "Kilderegister",
      completePath: "Dokumenteret sti",
      selectedPath: "Udvalgte milepæle",
      formation: "Grenens dannelse",
      tmrca: "TMRCA for nutidige testere",
      testers: "Nutidige testere",
      direct: "Fagfællebedømt kontekst",
      illustrative: "Leverandør-illustration",
      result: "Resultat",
      precision: "Præcision",
      evidenceState: "Evidensstatus",
      test: "Datasæt",
      measure: "Mål",
      note: "Fortolkningsnote",
    },
    v4: {
      eyebrow: "En evidensrejse · Simon",
      title: "Ét genom er ikke én historie.",
      lede: "Gå fra hundredtusindvis af autosomale markører til to enkelte arvelinjer — og mærk tidsskalaen ændre sig under fødderne.",
      begin: "Begynd rejsen",
      scene1: "01 · Testene",
      scene1Title: "Tre instrumenter ser på tre forskellige arvemønstre.",
      scene1Body: "Family Finder måler markører på tværs af autosomerne. mtFull følger én ubrudt morlinje. Big Y følger én farlinje. De mødes i en person, ikke i det, de måler.",
      scene2: "02 · Befolkningsestimatet",
      scene2Title: "Det bredeste signal peger nordpå.",
      scene2Body: "Nioghalvfems procent ligner skandinaviske referencebefolkninger. To mærkater ligger under én procent — synlige som spor, aldrig pustet op til præcise skiver.",
      scene3: "03 · Oldtidens europæere",
      scene3Title: "Jægere, bønder og derefter stepperelateret arv.",
      scene3Body: "En leverandørmodel opdeler de europæiske autosomer i tre dybe strømme. Procenterne beskriver statistiske komponenter; oldtidsgenomer giver historisk kontekst, ikke navngivne forfædre.",
      scene4: "04 · Morlinjen",
      scene4Title: "En tråd båret af mødre når en lille middelaldergren.",
      scene4Body: "Den terminale mtDNA-gren er U5b1b1a+7385+16519. Tidsestimatet har centrum i 836 e.Kr. med usikkerhed fra 505 til 1127 e.Kr.",
      scene5: "05 · Farlinjen",
      scene5Title: "Et atlantisk egetræ snævrer ind til tre nutidige testere.",
      scene5Body: "R-BY67151 blev dannet fra en ældre gren længe før den estimerede fælles forfader for nutidens testere. VCF-filen støtter alle 32 definerende varianter; to har kvalitetsflag.",
      scene6: "06 · Grænsen",
      scene6Title: "Evidens kan orientere en søgning. Den kan ikke navngive de manglende mennesker.",
      scene6Body: "Lande er selvrapporterede spor, datoer er sandsynlighedsintervaller, og dybe fælles knuder er ikke nært slægtskab. Det rå DNA forbliver privat; rejsen viser kun kontrollerede aggregater.",
      evidenceTray: "Åbn evidenssporet",
      closing: "Historien bliver mere nyttig, når usikkerheden er en del af kortet.",
    },
  },
} as const;

export function getEvidenceCopy(locale: Locale) {
  return copy[locale];
}
